### PR TITLE
Changes for displaying pull request and build number

### PR DESCRIPTION
**Pull request by mkarthik90**
[QSTR-113] Changes for displaying pull request and build number

### CODE REVIEW

**Comment by mkarthik90** [comment]
retest this please

**Comment by jdamerow** [comment]
ok to test

**Comment by jdamerow** [comment]
Can we fix the layout on the pages other than the login page (should be in the footer):
image

**Comment by mkarthik90** [comment]
@jdamerow  Made changes as per your comments

**Comment by jdamerow** [comment]
ups, forgot aobut this one. please resolve conflicts.

**Comment by mkarthik90** [comment]
@jdamerow  resolved merge conflicts

**Comment by jdamerow** [comment]
ok to test

**Pull request merged**
